- hosts: docker
  become: yes
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes

    - include_role:
        name: geerlingguy.docker

    - name: Install Docker python library
      pip:
        name: docker-py

    - include_role:
        name: andrewrothstein.docker-compose
