---
- hosts: web
  become: yes
  gather_facts: no
  tasks:
    - name: Install firewalld
      apt:
        name: firewalld
        state: latest
        update_cache: yes
    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
