--- # Bootstrap Nginx
- hosts: web
  become: yes
  tasks:
    - debug:
        var: target_service
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
      notify:
        - Restart nginx
    - name: Create index.html
      file:
        name: /var/www/html/index.html
        state: touch
    - name: Add content to index file
      lineinfile:
        line: "{{ ansible_hostname }}"
        path: /var/www/html/index.html
      notify:
        - Restart nginx
      register: task_debug
    - debug:
        msg: "Output of linefile is: {{ task_debug }}"

  handlers:
    - name: Start and enable Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
      listen:
        "Restart nginx"
