---
- hosts: web
  become: yes
  vars:
    userFile: /tmp/users.list
  tasks:
    - name: Create users
      user:
        name: "{{item}}"
        shell: /bin/bash
        ssh_key_file: .ssh/id_rsa
      with_items:
        - sam
        - john
        - eva
    - name: Create a file
      file:
        path: "{{userFile}}"
        state: touch
    - name: List users
      lineinfile:
        path: "{{userFile}}"
        line: "{{item}}"
      with_items:
        - "{{stuff}}"
        - "{{faculty}}"
        - "{{others}}"
