---
# Bootstrap Reverse proxy server
- hosts: web
  become: yes
  vars:
    web_service: apache2
  tasks:
    - debug:
        var: web_service
    - name: Install WEB
      apt:
        name: "{{ web_service }}"
        state: latest
      notify:
        - Restart web
    - name: Create index.html
      file:
        name: /var/www/html/index.html
        state: touch
    - name: Add content to index file
      lineinfile:
        line: "{{ ansible_hostname }}"
        path: /var/www/html/index.html
      notify:
        - Restart web
      register: task_debug
    - debug:
        msg: "Output of linefile is: {{ task_debug }}"

  handlers:
    - name: Start and enable WEB
      service:
        name: "{{ web_service }}"
        state: restarted
        enabled: yes
      listen:
        "Restart web"
